#
# Copyright (c) 2016-2026 B-Open Solutions srl - https://bopen.eu
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

try:
    # NOTE: the `version.py` file must not be present in the git repository
    #   as it is generated by setuptools at install time
    from .version import __version__
except ImportError:
    # Local copy or not installed with setuptools
    __version__ = "999"

# import all API functions and constants
from .datasource import (
    CACHE_DIR,
    DEFAULT_GDAL_OPTIONS,
    DEFAULT_OUTPUT,
    DEFAULT_PRODUCT,
    MARGIN,
    PRODUCTS,
    RETIRED_PRODUCTS,
    ProductRetiredError,
    clean,
    clip,
    dataset,
    distclean,
    info,
    resolve_cache_dir,
    seed,
)
from .util import TOOLS, check_call_make, selfcheck

__all__ = [
    "CACHE_DIR",
    "DEFAULT_GDAL_OPTIONS",
    "DEFAULT_OUTPUT",
    "DEFAULT_PRODUCT",
    "MARGIN",
    "PRODUCTS",
    "RETIRED_PRODUCTS",
    "TOOLS",
    "ProductRetiredError",
    "__version__",
    "check_call_make",
    "clean",
    "clip",
    "dataset",
    "distclean",
    "info",
    "resolve_cache_dir",
    "seed",
    "selfcheck",
]
